# Generated by Django 3.2 on 2022-06-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_order',
            field=models.BooleanField(default=False),
        ),
    ]
