# Generated by Django 3.2 on 2022-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
