# Generated by Django 3.2 on 2022-06-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6, null=True),
        ),
    ]
